trigger:
  branches:
    include:
      - main

variables:
  # Azure Container Registry details
  ACR_NAME: feedbackacr123.azurecr.io
  IMAGE_NAME: feedback-backend-app-na
  TAG: $(Build.BuildId)
  PORT: 3000

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Checkout code
- task: Checkout@1
  displayName: 'Checkout Repo'

# Step 2: Login to Azure Container Registry
- task: Docker@2
  displayName: 'Login to Azure Container Registry'
  inputs:
    containerRegistry: 'acr-service-conn'
    command: 'login'

# Step 3: Build Docker Image
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    containerRegistry: 'acr-service-conn'
    repository: '$(ACR_NAME)/$(IMAGE_NAME)'
    Dockerfile: 'Dockerfile'
    tags: |
      $(TAG)
      latest

# Step 4: Push Docker Image to ACR
- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    command: 'push'
    containerRegistry: 'acr-service-conn'
    repository: '$(ACR_NAME)/$(IMAGE_NAME)'
    tags: |
      $(TAG)
      latest

# Step 5: Deploy to Azure Web App (Container)
- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'azure-resource-conn'
    appName: 'feedback-backend-app-na'
    containers: |
      $(ACR_NAME)/$(IMAGE_NAME):latest
