name: Deploy Static Frontend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'feedback-frontend-app-na'  # Azure Web App Name
          slot-name: 'Production'
          package: './frontend'                # Path to your HTML folder
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C7046A8DF05F42DC9AA8323D9F2C8C36 }}
